Milestone: Library project
newhorizon-tech/library pull request #1
Opened 2021-02-18 10:19 UTC by newhorizon-tech

Concepts used

- Let and const variables
- Functions
- Arrow functions 
- Objects
- Object constructors
- DOM manipulation 

Functions 

- Add new books to the Library
- Display the books in the library
- Toggle the read status of a book
- Delete an existing book

2021-02-18 15:50 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello @newhorizon-tech  & @dasileker 👋 

The project looks solid. Good job. 
One more change before we proceed. The changes touch on the need to have the code modularised and some optional changes of having persistent data by employing the localStorage API and form validations 👇 
### Happy coding 💻 
#### Chrisian Otieno (CR)

2021-02-18 15:50 UTC, christianotieno commented on js/index.js
> +const myLibrary = [];
## Modularise this module
* [ ] Kindly keep the application logic separated from DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright) by modularising the `index.js` module into separate modules to achieve this.

2021-02-18 15:50 UTC, christianotieno commented on js/index.js
> +
## Optional Changes
- [ ] It would be great if the form had some form of validations, in that a user does not get to create an empty book as is the case below. 👇 
![Screenshot 2021-02-18 184118](https://user-images.githubusercontent.com/22345961/108382080-7fdef880-7219-11eb-8d2f-ecf2d612bbd7.png)


- [ ]  Can the project have data persistence during the saving, retrieving, and updating of the library books using the localstorage API (https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/localstorage_stretch_requirement.png) from [Odin Project](https://www.theodinproject.com/courses/javascript/lessons/library))?

2021-02-19 05:40 UTC, voscarmv requested changes
# Impressive work. 💻 👀 ✨ 

## However, there are some changes required 👀 🧰 🔨 🔧 

- As the previous TSE mentioned, we should try to keep our app logic separate from our DOM constructs. You seem to only have moved everything to the `dom.js` file, but the DOM stuff is still mixed with the app logc. I've marked all the methods that correspond to DOM stuff, and all the methods that correspond to app logic, to help you categorize them and separate them into different modules. Please read my code comments for details.
### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-02-19 05:40 UTC, voscarmv commented on src/dom.js
> +  });
This here represents app logic. Please move this to a file containing the app logic.

2021-02-19 05:40 UTC, voscarmv commented on src/dom.js
> +  });
This also corresponds to app logic. Please move this to an app logic module.

2021-02-19 05:40 UTC, voscarmv commented on src/dom.js
> +};
All this is DOM construction. This is placed correctly here in `dom.js`

2021-02-19 14:46 UTC, Temmarie approved these changes
## Status: Approved :heavy_check_mark:

### Hi @newhorizon-tech  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-02-19 18:22 UTC, merged